x-cli: &x-cli
  image: ghcr.io/range3/translatable:master
  # build: .
  volumes:
    - ./data:/app/data
  env_file:
    - .env
  command: ["sh", "-c", "while true; do sleep 30; done"]

services:
  cpu:
    <<: *x-cli
  gpu:
    <<: *x-cli
    shm_size: '5g'
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
